fix: providing coverage for draft and publish Strapi content types
VirtusLab/strapi-plugin-navigation pull request #45
Opened 2021-03-05 13:03 UTC by cyp3rius

## Ticket

https://github.com/VirtusLab/strapi-plugin-navigation/issues/42
https://github.com/VirtusLab/strapi-plugin-navigation/issues/44

## Summary

What does this PR do/solve? 

- adds coverage for built-in Strapi draft & publish flow
- prevents 500 error when content type entity has been accidentally removed
- filter outs removed and draft entities from render output

## Test Plan

- play with single & collection types
- play with the publish status

2021-03-07 17:15 UTC, Kronos66 requested changes

2021-03-07 17:15 UTC, Kronos66 commented on services/utils/functions.js
> +      return item.type === itemType.INTERNAL ? isRelatedDefinedAndPublished  : true
I think I see some problem here what happens if I have a collection type/single type without draft/publish flow and the item is internal? I think this method will filter that item

2021-03-08 07:53 UTC, cyp3rius commented on admin/src/containers/View/utils/parsers.js
> +      related: item.related,
I just don't want to pass the whole object there :)

2021-03-08 07:53 UTC, cyp3rius commented on admin/src/containers/View/components/NavigationItemPopup/index.js
> +  const appendLabelPublicationStatus = (label = '', item = {}, isCollection = false) => {
Let's leave it for later as not crucial :)

2021-03-08 07:54 UTC, cyp3rius commented on services/navigation.js
> +            const itemsCountOrBypass = isSingleTypeWithPublishFlow ? await strapi.query(uid).count({
as we've been talking :)

2021-03-08 10:19 UTC, Kronos66 approved these changes

2021-03-08 10:24 UTC, merged